sonar.organization=velizartodorov
sonar.projectKey=velizartodorov_velizartodorov.github.io

sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.test.tsx,src/setupTests.ts
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
