import { ELENA, GHENT, GHENT_CONTRACT, HASSELT_REMOTE, RUSE, currentDate } from "../common/utils";
import { Type } from "./type";
import { Employment } from "./employment";

export const employments: Employment[] = [
    {
        position: "Full-Stack Developer",
        company: 'Docbyte',
        type: Type.Service,
        place: GHENT,
        icon: '/employments/docbyte.jpg',
        period: {
            start: new Date(2024, 3),
            end: currentDate()
        },
        description: [
            `
            Docbyte is a leading organization that provides intelligent technologies 
            to various knowledge worker organizations, from banks and insurers to any enterprise
            in the field of information security, preservation, and document processing.
            Their platform helps to automate document processes and preserve digital information, 
            enabling the clients to prepare for a fully digital future.`,
            ``,
            `Description 📚`,
            ``,
            `• Migrating legacy on-premise apps towards cloud serverless AWS Lambda solution`,
            `• Integrating Amazon Textract as an OCR solution for the cloud infrastructure`,
            `• Documenting the flow in C4 architectural diagram`,
            `• Following ISO 27001/9001 standards in the ecosystem of Docbyte`,
            ``,
            `Technologies - Cloud Solution 🔧`,
            ``,
            `• Language/framework: Java 17 (Quarkus framework), Python 3`,
            `• API Tools: AWS API Gateway`,
            `• PDF Manipulation library: Aspopse`,
            `• Dependency management: Maven`,
            `• Containerization: none`,
            `• Testing framework: JUnit 4`,
            `• Deployments: AWS Lambda deployment packages`,
            `• Storage: AWS Amazon S3`,
            `• Event bus: Amazon EventBridge/CloudWatch Events`,
            `• Artifact repository: AWS CodeArtifact`,
            `• Pipeline: AWS CodePipeline`,
            `• Building: AWS CodeBuild`,
            `• Database: AWS DynamoDB, PostgreSQL`,
            `• Database management: AWS Management Console`,
            `• Application server: Serverless 😉`,
            `• Architecture: Serverless, microservices`,
            `• Identity/access management: KeyCloak`,
            `• OCR: Google AI, Amazon Textract, Native OCR`,
            `• Front-end: Angular 12`,
            `• Version control: Git, AWS CodeCommit`,
            `• IDE: IntelliJ, VS Code, PyCharm`,
            `• Diagram schematization and documentation: draw.io`,
            `• Development methodology: Pair/solo programming`,
            `• Task management: JIRA`,
            `• Time logging: JIRA Tempo`,
            `• Production methodology: Scrum, sprints of two weeks`,
            ``,
            `Technologies - Legacy on-premise solution 🔧`,
            ``,
            `• Language/framework: C#, .NET 4.5, OpenText Captiva`,
            `• OCR: Google AI`,
            `• Database: Microsoft SQL Server`,
            `• Ecosystem: Microsoft services/batch processing`,
            `• Version control: Git, BitBucket`,
            ``,
            `References 📌`,
            ``,
        ],
        references: [
            { value: "Docbyte N.V.", href: "https://www.docbyte.com/" },
            { value: "Aspose.PDF | Java PDF Document Processing Class Library", href: "https://releases.aspose.com/pdf/java/" }
        ]
    },
    {
        position: "Java Software Crafter",
        company: 'Continuum Consulting NV',
        type: Type.Consultancy,
        place: HASSELT_REMOTE,
        icon: '/employments/continuum.jpg',
        period: {
            start: new Date(2023, 4),
            end: new Date(2024, 0)
        },
        description: [
            `Description 📚`,
            ``,
            `Joined the Continuum tribe, consulting clients using Java based applications.`,
            ``,
            `• Research & development on internal applications, such as E-Tribe Tool and HR Interview Tool`,
            `• Experimenting with Docker, Kubernetes and tryouts for migrating from Elastic BeanStalk to Kubernetes`,
            `• Updating documentation`,
            ``,
            `Technologies 🔧`,
            ``,
            `• Language/framework: Java 17, Spring Boot 2.6.7`,
            `• API Tools: Swagger`,
            `• Dependency management: Gradle`,
            `• Containerization: Docker`,
            `• DevOps: Elastic BeanStalk`,
            `• Testing framework: JUnit 4`,
            `• Deployments: Confluence Bamboo, Azure`,
            `• Database: PostgreSQL, Amazon DynamoDB (serverless, key-value NoSQL database)`,
            `• Application server: Apache Tomcat 8`,
            `• Architecture: Microservices, Client-server`,
            `• Persistence: Spring Data JPA/R2DBC, Hibernate`,
            `• Database management: Flyway`,
            `• Identity/access management: KeyCloak (0Auth 2.0)`,
            `• Front-end: Angular 12`,
            `• Version control: Git, GitHub`,
            `• IDE: IntelliJ, VS Code`,
            `• Diagram schematization and documentation: Mermaid.js`,
            `• Development methodology: Pair/solo programming`,
            `• Time logging: Teamleader`,
            `• Production methodology: Kanban`,
            ``,
            `References 📌`,
            ``,
        ],
        references: [
            { value: "Continuum Consulting NV", href: "https://www.continuum.be/en/" }
        ]
    },
    {
        position: "Java Developer",
        company: 'Securex',
        type: Type.Product,
        place: GHENT_CONTRACT,
        icon: '/employments/securex.png',
        period: {
            start: new Date(2023, 6),
            end: new Date(2023, 11)
        },
        description: [
            `Description 📚`,
            ``,
            `Joined Securex as an external Java software developer. 
            Worked on an internal application (Wellbeing), related to sending surveys and assessments to the employees and employers of a company, so that both can receive reports and further help for their medical status.`,
            ``,
            `Technologies 🔧`,
            ``,
            `• Language/framework: Java 11/17, Spring Boot 2.6`,
            `• API Tools: Apicurio Studio, Swagger`,
            `• Dependency management: Gradle`,
            `• Testing framework: Groovy-Spock`,
            `• CI/CD: Atlassian Bamboo`,
            `• Data monitoring: Elastic Kibana`,
            `• Deployments: Azure`,
            `• Database: Oracle, Microsoft SQL Server`,
            `• Application server: Apache Tomcat`,
            `• Architecture: Distributed microservices, Spring Cloud Gateway, Netflix Zuul API (Eureka)`,
            `• Message queues/notifications:  Amazon Simple Queue Service (SQS) / Amazon Simple Notification Service (SNS)`,
            `• Persistence: Spring Data JPA, Hibernate`,
            `• Database management: Liquibase`,
            `• Front-end: React, React Native (mobile app)`,
            `• Version control: Git, BitBucket`,
            `• IDE: IntelliJ, VS Code, DbVisualizer Pro 11.0.5`,
            `• Development methodology: Pair/solo programming`,
            `• Production methodology: Scrum with 2-week sprints (planning, retros), SAFe (Scaled agile framework)`,
            `• Time logging: Jira`,
            ``,
            `References 📌`,
            ``,
        ],
        references: [
            { value: "Securex", href: "https://www.securex.be/en" },
            { value: "BeWell application", href: "https://www.securex.be/nl/personeelsbeleid/welzijn-op-het-werk" }
        ]
    },
    {
        position: "Software Developer",
        company: 'Unified Post',
        type: Type.Product,
        place: GHENT,
        icon: '/employments/unified_post.jpeg',
        period: {
            start: new Date(2019, 3),
            end: new Date(2023, 3)
        },
        description: [
            `Description 📚`,
            ``,
            `• ADMS was acquired by Unified Post. Working on the Integration Portal, 
            configuration app for connecting 3rd party apps to the Unified Post flows`,
            `• Setting-up JIRA flow + Bitbucket integration, Git Gitflow`,
            `• Working on accountancy simulation app using multi-tenancy architecture (Spring Boot)`,
            `• Documenting and schematizing the flow using C4 diagrams, updating README-s`,
            `• Creating TestRail cases`,
            ``,
            `Technologies 🔧`,
            ``,
            `• Language/framework: Java 8/11, Spring Boot 2.6.7, Project Reactor`,
            `• API tool: Swagger`,
            `• Dependency management: Maven, Gradle`,
            `• Testing framework/tools: JUnit 4/5, Mockito, TestRails (testcases), Selenium`,
            `• CI/CD: BitBucket Pipelines`,
            `• Database: PostgreSQL`,
            `• Application server: Apache Tomcat 8`,
            `• Architecture: Microservices`,
            `• Persistence: Spring Data JPA, Hibernate`,
            `• Caching: Redis`,
            `• Database management: Liquibase, Flyway`,
            `• Identity/access management: KeyCloak (0Auth 2.0)`,
            `• Front-end: Angular 12`,
            `• IDE: IntelliJ, VS Code, DBeaver`,
            `• Diagram schematization and documentation: Draw.io, C4 Structurizr, Markdown`,
            `• Production methodology: Kanban & Scrum`,
            ``,
            `References 📌`,
            ``,
        ],
        references: [
            { value: "Unifiedpost", href: "https://www.unifiedpost.com/" },
            { value: "Banqup", href: "https://www.banqup.com/" }
        ]
    },
    {
        position: "Java Developer",
        company: 'ADM Solutions',
        type: Type.Product,
        place: GHENT,
        icon: '/employments/adm_solutions.jpg',
        period: {
            start: new Date(2018, 10),
            end: new Date(2019, 2)
        },
        description: [
            `Description 📚`,
            ``,
            `• Integrating, developing and improving automatized invoice/dossier flows with external services such as BillToBox (BanqUp), ELO and accountancy packages`,
            `• Documenting and schematizing the flow using UML diagrams`,
            `• Working on InvoiceFlow, monolitic application which distributes invoices towards different accountancy packages like Expert-M, Adsolut, ExactOnline, BoCount, Wings Online and also persists them in a document management system called ELO`,
            `• Working on DossierFlow, monolitic application which reads information about user dossiers from Adsolut and imports them in ELO`,
            `• Migrating Java applications from SVN to Git`,
            ``,
            `Technologies 🔧`,
            ``,
            `• Language: Java 8`,
            `• Testing framework: JUnit 4`,
            `• Database: Microsoft SQL Server 2008-2012`,
            `• Application server: Apache Tomcat 8`,
            `• OS: Windows Server 2008-2012`,
            `• External API: ELO API`,
            `• Persistence: Java Database Connectivity (JDBC)`,
            `• Architecture: Java Servlet`,
            `• Front-end: Java Server Pages (JSP) + jQuerry/Ajax`,
            `• Version Control: SVN/Git, BitBucket`,
            `• IDE: Eclipse`,
            `• Diagram schematization: Draw.io, MS Visio`,
            `• Development methodology: Pair programming`,
            `• Production methodology: Kanban`,
            ``,
            `References 📌`,
            ``,
        ],
        references: [
            { value: "ADM Solutions", href: "https://web.archive.org/web/20181111090144/https://adm-solutions.eu/nl/" },
            { value: "ELO", href: "https://www.elo.com/en-de.html" }
        ]
    },
    {
        position: "Erasmus+ C# Developer Trainee",
        company: 'BIKEMA',
        type: Type.ResearchAndDevelopment,
        place: GHENT,
        icon: '/employments/bikema_small.png',
        period: {
            start: new Date(2018, 6),
            end: new Date(2018, 9)
        },
        description: [
            `Description 📚`,
            ``,
            `• Overview of C# programming concepts and approaches in .NET 4.0 and higher (Visual Studio 2015/17)`,
            `• Design and implementation of C#-based software`,
            `• Improving workflow and providing support functions`,
            `• Performing tests over C#-based software components`,
            `• Development methodology: Pair programming`,
            `• Production methodology: Kanban`,
            ``,
            `References 📌`,
            ``,
        ],
        references: [
            { value: "Erasmus+", href: "https://erasmus-plus.ec.europa.eu/" },
            { value: "University of Ruse", href: "https://www.uni-ruse.bg/en" },
            { value: "BIKEMA information", href: "http://fetch.ecs.uni-ruse.bg/?cmd=gsProfile&user=FERNAND" },
            { value: "Lotuswebtec.com", href: "https://www.lotuswebtec.com/en/" }
        ]
    },
    {
        position: "Full-Stack Developer",
        type: Type.Startup,
        company: 'DSI Ltd.',
        place: RUSE,
        icon: '/employments/dsi.png',
        period: {
            start: new Date(2017, 6),
            end: new Date(2018, 4)
        },
        description: [
            `Description 📚`,
            ``,
            `• Kozelat.com/Outletpc.bg – OpenCart 2.3 (PHP 7.1/Bootstrap 3) shops – development and support`,
            `• MiAudit – (Laravel 4.2/Bootstrap 3) – system for audit and management of cleaning companies in UK`,
            `• Git/Unix shell, FileZilla, PuTTY remote maintenance of company servers`,
            `• Project management system (Redmine) & web hosting administration (Digital Ocean)`,
            `• Development methodology: Pair programming`,
            `• Production methodology: Kanban`,
            ``,
            `References 📌`,
            ``,
        ],
        references: [
            { value: "DSI Ltd - Developing Software Innovations", href: "https://dsi.bg/en/" },
            { value: "Kozelat.com", href: "https://kozelat.com/" },
            { value: "Outletpc.bg", href: "https://outletpc.bg/" },
            { value: "MiAudit", href: "https://miaudit.com/" }
        ]
    },
    {
        position: "Computer Repair Technician",
        type: Type.Service,
        company: 'Telnet Ltd.',
        place: ELENA,
        icon: '/employments/telnet.png',
        period: {
            start: new Date(2015, 6),
            end: new Date(2015, 8)
        },
        description: [
            `Description 📚`,
            ``,
            `• software and hardware fixing PC-s, laptops, mobile phones, tables`,
            `• changing, cleaning and maintaining hardware components of computer configurations`,
            `• software reinstallation, backup and maintance`,
            `• creating hardware parts list for PC configuration based on customer requirements`,
            ``,
            `The company has already been acquired by the largest telecom in Bulgaria – Vivacom (2024). 💡`,
            ``,
            `References 📌`,
            ``,
        ],
        references: [
            { value: "Telnet", href: "https://telnet.bg/en/pc/home/p1/.html" },
            { value: "Vivacom", href: "https://www.vivacom.bg/bg/telnet" },
        ]
    }
];